### ISSUE TITLE
How to do user authentication with github?

### ISSUE THREAD

**Issue by joenayjoe** [improbable-eng/grpc-web#105]
I need to authenticate user with Github. But I am having difficult time in understanding how to do it in `grpc-web`. I google it for several times and asked in [stackoverflow](https://stackoverflow.com/questions/47340998/how-to-use-oauth2-for-user-authentication-in-grpc), but no luck.  I will appreciate if anyone can give me an example or any sort of help.

**Comment by easyCZ** [comment]
Hey @joenayjoe ,

Could you please clarify the problem you are having? From what you mention, it does not look like a problem with grpc-web itself but rather how to perform user authentication with Github in Go.

Here are some resources that may help https://developer.github.com/v3/guides/getting-started/#authentication

I will close this issue as it does not appear to be directly related to grpc-web. If you feel this is not the case please feel free to comment below and we can take it from there.

**Comment by joenayjoe** [comment]
Hi @easyCZ ,
Ok I will try to explain my problem. When a user clicks the link to log in with Github, he is redirected to Github authorization endpoint. Upon authorizing with user name and password, the user is redirected back to a callback URL How can I intercept that callback from grpc_web server to get the auth token? Since the callback is not a grpc method, I am not quite sure how to get  the information from the callback. 
May be I am messing up REST with gRPC.
Thanks

**Comment by easyCZ** [comment]
Thanks for clarification. Looking to give you an example now. Reopening

**Comment by easyCZ** [comment]
Hi @joenayjoe,

You can provide custom non-grpcweb functionality on the same server.
In the example you can provide a custom handler for any request that reaches the grpcweb server.
https://github.com/improbable-eng/grpc-web/blob/eda5103aa449bf449977da5879189f9b74940b23/example/go/exampleserver/exampleserver.go#L41 

For example, we can do the following, since we have access to the request:
```
handler := func(resp http.ResponseWriter, req *http.Request) {

		if req.URL.Path == "/auth" {
			fmt.Fprintf(resp, "Hi there, I love %s!", req.URL.Path[1:])
			return
		}
		wrappedServer.ServeHTTP(resp, req)
	}
```

This allows us to bypass the wrapped server and handle any request. You can get more fancy with this by using [chi](https://github.com/go-chi/chi) or [echo](https://github.com/labstack/echo). Let me know if that solves your problem

**Comment by joenayjoe** [comment]
@easyCZ ,
Thank you for the tips. I tried to make a call to a custom URL and it indeed works.

**Comment by easyCZ** [comment]
@joenayjoe That's great news. Closing.
