### ISSUE TITLE
Can't increase deadline time using grpc.invoke method

### ISSUE THREAD

**Issue by tylern206** [improbable-eng/grpc-web#1062]
Version: 
 "@improbable-eng/grpc-web": "^0.14.0",
 "@improbable-eng/grpc-web-react-native-transport": "^0.14.0",

I'm running across a problem where I'm getting a grpc request "Deadline" error and found that I need to increase set the deadline time. However, I wasn't able to see a way how to do it from the documentation given on https://github.com/improbable-eng/grpc-web. Is there any way I can set the deadline time? 

```
grpc.invoke(InventoryOperations.SearchObjects, {
        request: inventorySearchQuery,
        host: hostIp,
        onHeaders: (headers: grpc.Metadata) => {
          // console.log("headers", headers);
        },
        onMessage: (message: InventorySearchResponse) => {
          // console.log("search object result", message.toObject());
        },
        onEnd: (
          code: grpc.Code,
          msg: string | undefined,
          trailers: grpc.Metadata
        ) => {
          console.log("grpc on end result", msg, grpc.Code[code]);
          reject({ msg, code: grpc.Code[code] });
        },
```
There is an example given on https://github.com/grpc/grpc-web on how to set the deadline, but I didn't see this as an option for the grpc.invoke method.

```
var deadline = new Date();
deadline.setSeconds(deadline.getSeconds() + 1);

client.sayHelloAfterDelay(request, {deadline: deadline.getTime()},
  (err, response) => {
    // err will be populated if the RPC exceeds the deadline
  });
```

Thanks,
Tyler

**Comment by johanbrandhorst** [comment]
Hi Tyler, thanks for your issue! As you can see in the grpc-web implementation you referenced (https://github.com/grpc/grpc-web/blob/1efe741695e7d330a4a56fe2e223fc027f83705c/javascript/net/grpc/web/grpcwebclientbase.js#L317-L335), the `deadline` property gets translated into the `grpc-timeout` header before being sent over the wire. The exact format of this header is specified in the gRPC HTTP/2 spec, which the gRPC-web spec inherits from: https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md. For example, to set a timeout of 1 minute, you would set a header like this:

```
Grpc-Timeout: 1M
```

Now, in order to set headers with our client, I believe you can specify them in the initial call, as is done in this test: https://github.com/improbable-eng/grpc-web/blob/c1971f71a28950d212b7ddc8df07b5563723031d/integration_test/ts/src/client.spec.ts#L172-L175.

However, gRPC timeouts (or deadlines) are additive, not immutable. If you are already suffering a deadline error, it's because a deadline is imposed somewhere in your call stack (maybe a proxy configuration, or HTTP server timeout). Adding another timeout will not remove it.

Hope that helps!

**Comment by tylern206** [comment]
Thanks for your quick reply! It turns out the envoy proxy server was causing the timeout. I had to add timeout: 0s on the envoy.yaml file and that fixed it.
