### ISSUE TITLE
General question about grpc-web

### ISSUE THREAD

**Issue by sulliwane** [improbable-eng/grpc-web#22]
I understand that the browser is lacking a feature to fully support grpc protocol (that may arrive in 2 years). I deduce that my only way to request data from grpc server using a browser is to go through a gateway...

So the gateway needs to talk HTTP on one side, and GPRC on the other...correct?

So the MAJOR barrier to bring grpc to the web is to have a robust gateway (would it be written in go, or c++...), the browser library to send the requests would be as easy as using fetch in recent browsers...

If I'm correct on these points, I don't understand how[ the official grpc-web-gateway](https://github.com/grpc/grpc-web/) (not open-sourced yet) could be still not following the last grpc-web specs, and why this present [grpcwebproxy](https://github.com/improbable-eng/grpc-web/tree/master/go/grpcwebproxy) seems to not be the "killer program" of this current repository?

I'm just trying to get some insights from the people who have a full picture of the whole situation, As I'm struggling to get a simple grpc unaryCall working over http....

Many thanks!

**Comment by mwitkow** [comment]
To clarify: gRPC is HTTP2. It's basically a calling convention on top of HTTP2.  The major barrier to adoption in web is not a gateway of any sort, but the fact that browsers do not expose low-level networking semantics. That is why the *current* [gRPC Web spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md) works around it in two ways:
 * encodes HTTP2 trailers as data streams, so you can get the responses (what the Go grpcwebproxy does)
 * it only supports server-side streams and unary RPCs (since there is no API in browsers to stream from client side)

The [grpc/grpc-web](https://github.com/grpc/grpc-web/) repo contains an implementation of a *past* spec, one that relied on base64 encoding. The gRPC team will be working on getting a proxy implementation of the *current* spec in the future. We provide an independent implementation of the *current* spec here.

**Comment by sulliwane** [comment]
Thank you for the clarification!
