### ISSUE TITLE
Strange messages in browser console

### ISSUE THREAD

**Issue by moabtools** [improbable-eng/grpc-web#412]
With every grpc query through grpc-web-proxy I see those errors in chrome console:

- Refused to get unsafe header "grpc-status"
- Refused to get unsafe header "grpc-message" 

But everything works as expected.
What's those messages means and how to hide it?
Last version of grpc-web-proxy win64.

**Comment by biril** [comment]
I believe this is a CORS issue. 

Solved by reconfiguring our gateway (or whatever component takes care of delivering CORS header to the client in your case) to expose `grpc-status` and `grpc-message` through the [`Access-Control-Expose-Headers
`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers).

Hope this helps.

**Comment by Globegitter** [comment]
Also just ran into this when running `grpcwebproxy --allow_all_origins`. Is this something that can be solved by the project here directly? Per default or maybe with another cli flag? I do not have any other component responsible for delivering CORS headers.

**Comment by Globegitter** [comment]
https://github.com/improbable-eng/grpc-web/issues/396 seems to be the same issue.

**Comment by Globegitter** [comment]
Using envoy with the default config that grpc-web provides does not have this issue - it would be nice if that could also be fixed with grpcwebproxy per default as I do like the simplicity of this proxy.

I actually tried to add the headers here: https://github.com/improbable-eng/grpc-web/blob/master/go/grpcweb/wrapper.go#L52 but it did not work. But I also do not really understand the comment so not entirely sure how I could fix this.
