### ISSUE TITLE
gRPC-Web stack choice, what are the long term compatibility plans?

### ISSUE THREAD

**Issue by vflopes** [improbable-eng/grpc-web#555]
Hello, first of all, thanks for this great project! I'll explain a little more about my use case (and the path that I've followed to get things working) so my question will make more sense:

1. I started a big project in a big company (really, really big) where we are building services with gRPC+Protobuf as communication protocol for backend and things are working majestically!
2. So now, we're building our frontend applications and we want to use gRPC as well (other solutions would be creating a proxy to translate gRPC calls into REST/JSON endpoints, which I think it is a really sad way 'cause we lost a lot of cool things/flexibility of gRPC and it would create an extra work to keep docs, mappings and etc between gRPC and REST, in other words, increased complexity without any real gain).
3. So we started to research and test some frontend stacks divided in two categories: proxy and client library.
4. As proxy we prefer Envoy as we already deal with it on Istio, **but** if this project requires a custom proxy I don't see any impediment that prevents us from changing it. We just have the caution to choose *production grade* tools.
5. As client library we first tested the Google's grpc-web library, but it seems to be really full of issues, slow development as they focus on internal cases instead of community reported issues/feature requests, and we had found some of them. So we started to test the Improbable's client, and is really doing great with Envoy, so we'll keep this library as our frontend client.

Now here are my questions:

1. Is there any LTS plan for this library or at some point Improbable and Google implementations will converge and just one of them will survive?
2. Is the proxy provided by Improbable on GA?
3. What are plans for long term compatibility with gRPC-Web protocol? If the Envoy implementation keeps following the protocol specs, can I be sure that Improbable would be too so they will be fully compatible?

I understand that Improbable implements few things to support bi-di communication like websockets that is not part of the "official" protocol spec, and it's really awesome that you guys are evolving on the edge of "gRPC for web", but will these things be kept as optional to keep the compatibility with Google's specification?

PS: we don't need now bi-di communication, I prefer to wait for browsers to mature their HTTP/2 support/APIs, 'cause dealing with stateful connections over HTTP/1.1 (like websocket is) is a huge complexity increment (from the backend/infrastructure viewpoint).

**Comment by johanbrandhorst** [comment]
Hi Victor,

Thanks for your kind words! The first thing you should do is read the latest grpc.io blog post on the state of grpc-web: https://grpc.io/blog/state-of-grpc-web/. It's still accurate.

The TL;DR of that post is that the grpc/grpc-web client is being pushed as the official one, and while this client will continue to be maintained as least as long as Improbable still has a need for it, it is not the primary client for new users.

That said, the two should remain compatible, and I've created a repo that tests the latest releases of each against each proxy: https://github.com/johanbrandhorst/grpc-web-compatibility-test. As you can see, the two are mostly compatible right now, so you should be able to confidently use this client together with the Envoy proxy filter.

The one benefit you get with the Improbable proxy, other than experimental websockets, is that you can run it as an in-process proxy in a Go gRPC server. This has other compromises, and since you're already using Envoy, it shouldn't be a benefit to you specifically (other than for local development, perhaps).

If you have anymore questions, I'd be happy to answer them on the [improbable-eng slack](https://join.slack.com/t/improbable-eng/shared_invite/enQtMzQ1ODcyMzQ5MjM4LWY5ZWZmNGM2ODc5MmViNmQ3ZTA3ZTY3NzQwOTBlMTkzZmIxZTIxODk0OWU3YjZhNWVlNDU3MDlkZGViZjhkMjc).
