### ISSUE TITLE
Question - I am not sure to understand how you setup the TLS part while initializing the client (typescript)

### ISSUE THREAD

**Issue by Emixam23** [improbable-eng/grpc-web#719]
Hi,

When I initialize the following client:

```
export class ContactAPIClient {
    readonly serviceHost: string;

    constructor(serviceHost: string, options?: grpc.RpcOptions);

   // ...
}
```

I do see the RpcOptions but I am quite lost about how from the RPC options you setup the TLS part, can you give me a link or some steps to follow, please?

Thanks

**Comment by johanbrandhorst** [comment]
In the browser client any TLS options have to be configured on the browser level, because we don't have access to the underlying network like you might have on other platforms. This essentially means that you will need to configure your server with a publically acceptable certificate (e.g. Let's Encrypt or one bought from a CA directly).

**Comment by softshipper** [comment]
@johanbrandhorst Could you please provide an example with `Let's Encrypt `?

**Comment by johanbrandhorst** [comment]
My grpc-web example repo uses the `autocert` package to set up a certificate with lets encrypt: https://github.com/johanbrandhorst/grpcweb-example/blob/93f68dcab6294294b9b1d0302685aa5263fd37c7/main.go#L82-L86. You can try it out here: https://grpcweb.jbrandhorst.com/.
