### ISSUE TITLE
Unable to deserialise message sent in `grpc-status-details-bin`

### ISSUE THREAD

**Issue by huysamen** [improbable-eng/grpc-web#799]
Following the practice of sending rich errors in the metadata trailer:

```go
return nil, status.ErrorProto(
	&spb.Status{
		Code:    int32(codes.InvalidArgument),
		Message: "some message",
		Details: []*anypb.Any{a},    // with `a` pointing to some instance of a message defined in proto
	},
)
```

In the response the `grpc-status-details-bin` is a base64 version of the details data, but it does not seem to be in the same format normal messages are returned.  Therefore, it is impossible to deserialise the data into something meaningful, in turn making it impossible to do rich errors.

**Comment by johanbrandhorst** [comment]
Are you using https://pkg.go.dev/github.com/golang/protobuf/ptypes#MarshalAny or https://pkg.go.dev/google.golang.org/protobuf@v1.25.0/types/known/anypb#MarshalFrom to marshal your message type into `any.Any`? Secondly, how are you attempting to decode the details? There's a discussion in https://github.com/grpc/grpc-web/issues/399#issuecomment-444547461 on how to unmarshal the details.

What are you suggesting the problem is exactly? With the client? The proxy?

**Comment by huysamen** [comment]
Ah great, thanks @johanbrandhorst - the double deserialization did the trick.
