### ISSUE TITLE
question: streaming

### ISSUE THREAD

**Issue by joeblew99** [improbable-eng/grpc-web#8]
thanks for doing this.

I noticed that it supports the 1 request, n responses pattern.
So, if i want to notify a client for whatever reason, i can use this pattern. Its basically exactly like a web socket in terms of patterns at least ?

What would be a use case example of what this library does not support in terms of "client streaming" ?

**Comment by mwitkow** [comment]
This is more of a question around gRPC streaming semantics:
http://www.grpc.io/docs/guides/concepts.html#bidirectional-streaming-rpc

Server-side streaming can be used when the response: 
 - comes at different times, e.g. when implementing a Watch pattern (asynchronous notifies)
 - you need to chunk up the response into smaller messages (gRPC supports 4MB message size), e.g. for streaming large lists/large 

Bi-di streaming (unsupported in gRPC-Web) is useful for:
 - client side updates (e.g. a game)
 - incremental computation when a client needs to make further decisions as to what results it wants

Client-side streaming (unsuported in gRPC-Web) is rarer. It's usually useful for:
 - chunked uploads (4MB size)
 - remote logging

You're right in saying that WebSockets is an existing piece of technology that gives you both. However, since we're using gRPC as the backbone of our APIs at Improbable (for CLI clients, microservices etc), as it provides easy to use auto-generated stubs in almost all major languages, we decided we wanted to use it from browsers to not have to "special case" it by implementing custom handlers just for the web.

You may find this useful:
https://cloud.google.com/apis/design/
